#ifndef TEST17_SFLSELECT_DSPF_H
#define TEST17_SFLSELECT_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct CUSTSFL3_buf {
    char CUSTNO[9] = {};
};

struct CUSTCTL3_buf {
};

#endif // TEST17_SFLSELECT_DSPF_H
