#ifndef TEST03_COND_DSPF_H
#define TEST03_COND_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct ORDRDSP_buf {
    char ORDNO[11] = {};
    char ERRMSG[79] = {};
};

#endif // TEST03_COND_DSPF_H
