#ifndef TEST04_DDS_SUBFILE_DSPF_H
#define TEST04_DDS_SUBFILE_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct EMPSFL_buf {
    char EMPNO[7] = {};
    char EMPNAME[31] = {};
    double SALARY = 0.0;
};

struct EMPCTL_buf {
    long SFLRCDNB = 0;
};

#endif // TEST04_DDS_SUBFILE_DSPF_H
