#ifndef TEST20_FIELD_BOUNDS_WARNING_DSPF_H
#define TEST20_FIELD_BOUNDS_WARNING_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct BADPOS_buf {
    char OFFSCREEN[9] = {};
    char TOOWIDE[21] = {};
    char VALID1[9] = {};
};

#endif // TEST20_FIELD_BOUNDS_WARNING_DSPF_H
