#ifndef TEST16_SFLOPTION_DSPF_H
#define TEST16_SFLOPTION_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct CUSTSFL2_buf {
    char OPTION[2] = {};
    char CUSTNO[9] = {};
};

struct CUSTCTL2_buf {
};

#endif // TEST16_SFLOPTION_DSPF_H
