#ifndef TEST21_DFTVAL_DSPF_H
#define TEST21_DFTVAL_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct MYREC_buf {
    char GREETING[11] = {};
    double QTY = 0.0;
    char SPARE1[6] = {};
};

#endif // TEST21_DFTVAL_DSPF_H
