#ifndef TEST13_ALIAS_DSPF_H
#define TEST13_ALIAS_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct ALIASTEST_buf {
    char CRYPTNM[9] = {};
};

#endif // TEST13_ALIAS_DSPF_H
