#ifndef TEST18_SFLNXTCHG_DSPF_H
#define TEST18_SFLNXTCHG_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct CUSTSFL4_buf {
    char OPTION[2] = {};
    char CUSTNO[9] = {};
};

struct CUSTCTL4_buf {
};

#endif // TEST18_SFLNXTCHG_DSPF_H
