#ifndef TEST15_CHANGE_BLANKS_DSPF_H
#define TEST15_CHANGE_BLANKS_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct CHGBLKTEST_buf {
    char FLDX[6] = {};
    long FLDQTY = 0;
};

#endif // TEST15_CHANGE_BLANKS_DSPF_H
