#ifndef TEST23_DDS_COLUMNS_DSPF_H
#define TEST23_DDS_COLUMNS_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct COLTEST_buf {
    char CUSTOMERNO[11] = {};
    char MSGLINE[41] = {};
    char DASHCONT[21] = {};
    char CODE[2] = {};
};

#endif // TEST23_DDS_COLUMNS_DSPF_H
