#ifndef TEST12_DATETIME_DSPF_H
#define TEST12_DATETIME_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct DTTEST_buf {
    char FLDDATE[11] = {};
    char FLDTIME[9] = {};
    char FLDTS[27] = {};
};

#endif // TEST12_DATETIME_DSPF_H
