#ifndef TEST25_FILEKEYS_DSPF_H
#define TEST25_FILEKEYS_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct INHERITS_buf {
    char FLDA[6] = {};
};

struct OVERRIDE_buf {
    char FLDB[6] = {};
};

#endif // TEST25_FILEKEYS_DSPF_H
