#ifndef TEST01_BASIC_DSPF_H
#define TEST01_BASIC_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct MAINMENU_buf {
    char OPTION[2] = {};
    char ERRMSG[79] = {};
};

#endif // TEST01_BASIC_DSPF_H
