#ifndef TEST24_INDARA_DSPF_H
#define TEST24_INDARA_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct INDREC_buf {
    char GREETING[11] = {};
};

#endif // TEST24_INDARA_DSPF_H
