#ifndef TEST07_VALIDATE_DSPF_H
#define TEST07_VALIDATE_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct TESTREC_buf {
    char GENDER[2] = {};
    long AGE = 0;
    long SCORE = 0;
};

#endif // TEST07_VALIDATE_DSPF_H
