#ifndef TEST14_COLHDG_DSPF_H
#define TEST14_COLHDG_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct COLHDGTEST_buf {
    char NAME1[11] = {};
    char NAME2[11] = {};
    char DUMMY[2] = {};
};

#endif // TEST14_COLHDG_DSPF_H
