#ifndef TEST26_SFLCTL_DSPF_H
#define TEST26_SFLCTL_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct ROWSFL_buf {
    char ITEM[9] = {};
};

struct ROWCTL_buf {
};

#endif // TEST26_SFLCTL_DSPF_H
