#ifndef TEST22_LITERAL_STYLE_DSPF_H
#define TEST22_LITERAL_STYLE_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct MYREC_buf {
    char DUMMY[2] = {};
};

#endif // TEST22_LITERAL_STYLE_DSPF_H
