#ifndef TEST08_AUTO_DSPF_H
#define TEST08_AUTO_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct AUTOTEST_buf {
    char FLD1[4] = {};
    char FLD2[4] = {};
    char FLD3[4] = {};
};

#endif // TEST08_AUTO_DSPF_H
