#ifndef TEST02_SUBFILE_DSPF_H
#define TEST02_SUBFILE_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct CUSTSFL_buf {
    char CUSTNO[11] = {};
    char CUSTNAME[31] = {};
    double CUSTBAL = 0.0;
};

struct CUSTCTL_buf {
};

#endif // TEST02_SUBFILE_DSPF_H
