#ifndef TEST11_CLRL_DSPF_H
#define TEST11_CLRL_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct FIRST_buf {
};

struct SECOND_buf {
    char DUMMY[2] = {};
};

#endif // TEST11_CLRL_DSPF_H
