#ifndef TEST10_PAGEKEY_DSPF_H
#define TEST10_PAGEKEY_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct PAGEKEYTEST_buf {
    char DUMMY[2] = {};
};

#endif // TEST10_PAGEKEY_DSPF_H
