#ifndef TEST07_VALIDATE_DSPF_H
#define TEST07_VALIDATE_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct TESTREC_buf {
    char GENDER[2] = {};
    double AGE = 0.0;
    double SCORE = 0.0;
};

#endif // TEST07_VALIDATE_DSPF_H
