#include "codegen.h"
#include <sstream>
#include <algorithm>
#include <cctype>

namespace dspf {

// ---- JSON helpers --------------------------------------------------------

static std::string jsonStr(const std::string& s) {
    std::string r = "\"";
    for (char c : s) {
        switch (c) {
            case '"':  r += "\\\""; break;
            case '\\': r += "\\\\"; break;
            case '\n': r += "\\n";  break;
            case '\r': r += "\\r";  break;
            case '\t': r += "\\t";  break;
            default:   r += c;      break;
        }
    }
    r += '"';
    return r;
}

static char dtypeChar(const DspfField& f) { return f.dtype; }

static std::string cppFieldType(const DspfField& f) {
    switch (f.dtype) {
        case 'B': return "long";
        case 'F': return "double";
        case 'S': // zoned
        case 'P': // packed
            if (f.dec > 0) return "double";
            return "long";
        default:  return "std::string";
    }
}

// ---- JSON descriptor -----------------------------------------------------

std::string emitJSON(const DspfFile& file) {
    std::ostringstream o;
    o << "{\n";
    o << "  \"name\": " << jsonStr(file.name) << ",\n";
    o << "  \"records\": [\n";

    for (size_t ri = 0; ri < file.records.size(); ri++) {
        const DspfRecord& rec = file.records[ri];
        o << "    {\n";
        o << "      \"name\": " << jsonStr(rec.name) << ",\n";
        o << "      \"title\": " << jsonStr(rec.title.empty() ? rec.name : rec.title) << ",\n";
        o << "      \"screen\": { \"rows\": " << rec.screenRows << ", \"cols\": " << rec.screenCols << " },\n";

        // Literals
        o << "      \"literals\": [\n";
        for (size_t i = 0; i < rec.literals.size(); i++) {
            const DspfLiteral& lit = rec.literals[i];
            o << "        { \"row\": " << lit.row
              << ", \"col\": " << lit.col
              << ", \"text\": " << jsonStr(lit.text) << " }";
            if (i + 1 < rec.literals.size()) o << ",";
            o << "\n";
        }
        o << "      ],\n";

        // Fields
        o << "      \"fields\": [\n";
        for (size_t i = 0; i < rec.fields.size(); i++) {
            const DspfField& f = rec.fields[i];
            std::string dtype_str(1, dtypeChar(f));
            o << "        {\n";
            o << "          \"name\": " << jsonStr(f.name) << ",\n";
            o << "          \"type\": " << jsonStr(dtype_str) << ",\n";
            o << "          \"len\": " << f.len << ",\n";
            o << "          \"dec\": " << f.dec << ",\n";
            o << "          \"io\": " << jsonStr(std::string(1, f.io)) << ",\n";
            o << "          \"row\": " << f.row << ",\n";
            o << "          \"col\": " << f.col << ",\n";
            o << "          \"keywords\": [";
            for (size_t ki = 0; ki < f.keywords.size(); ki++) {
                o << jsonStr(f.keywords[ki]);
                if (ki + 1 < f.keywords.size()) o << ", ";
            }
            o << "]\n";
            o << "        }";
            if (i + 1 < rec.fields.size()) o << ",";
            o << "\n";
        }
        o << "      ],\n";

        // Keys
        o << "      \"keys\": [\n";
        for (size_t i = 0; i < rec.keys.size(); i++) {
            const DspfKey& k = rec.keys[i];
            o << "        { \"key\": " << jsonStr(k.key)
              << ", \"indicator\": " << k.indicator << " }";
            if (i + 1 < rec.keys.size()) o << ",";
            o << "\n";
        }
        o << "      ]\n";

        o << "    }";
        if (ri + 1 < file.records.size()) o << ",";
        o << "\n";
    }

    o << "  ]\n";
    o << "}\n";
    return o.str();
}

// ---- C++ header ----------------------------------------------------------

std::string emitHeader(const DspfFile& file) {
    std::ostringstream o;
    std::string guard = file.name + "_DSPF_H";
    for (auto& c : guard) c = (char)toupper((unsigned char)c);
    // Replace non-alnum with _
    for (auto& c : guard) if (!isalnum((unsigned char)c)) c = '_';

    o << "#ifndef " << guard << "\n";
    o << "#define " << guard << "\n\n";
    o << "#include <string>\n\n";
    o << "// Auto-generated by dspfc — do not edit\n\n";

    for (const DspfRecord& rec : file.records) {
        o << "struct " << rec.name << "_buf {\n";
        for (const DspfField& f : rec.fields) {
            if (f.io == 'H') continue; // hidden fields are not in the buffer
            std::string ct = cppFieldType(f);
            if (ct == "std::string") {
                // Fixed char array (len + 1 for NUL)
                o << "    char " << f.name << "[" << (f.len + 1) << "] = {};\n";
            } else if (ct == "long") {
                o << "    long " << f.name << " = 0;\n";
            } else {
                o << "    double " << f.name << " = 0.0;\n";
            }
        }
        o << "};\n\n";
    }

    o << "#endif // " << guard << "\n";
    return o.str();
}

} // namespace dspf
